
server:
  port: 9701
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: system
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 100000
      leak-detection-threshold: 10000
  application:
    name: spring-security-jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect 
  main:
     allow-bean-definition-overriding: true
  profiles:
    active:
    - jwt

security:
  jwt:
    token:
      secretkey: siops
      expire-length: 300000 # 1 Minute Duration by Default i.e  60 seconds * 1000 miliseconds
    
    

